# Generated by Django 4.1.7 on 2023-10-24 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebookapi', '0002_remove_note_alerted'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='email_reminder',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
