# Generated by Django 4.1.7 on 2023-10-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notebookapi', '0003_note_email_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='reminder',
            field=models.BooleanField(default=False),
        ),
    ]
